### ISSUE TITLE
Custom Checkbox for each item - Enhancement

### ISSUE THREAD

**Issue by 9812ga98sd** [rektdeckard/huebert#5]
Another options may be:

A tickbox to just show the lights not the group and lights.  I have 6 lights but 12 items. A Custom menu option, then just checkbox which lights\groups to show and also with the other options too. Make them all checkbox for that Custom Menu. 
so above lights I would add a new menu item, Custom. In that each section (lights, device info etc) has a checkbox to show it or not. Then the same with the items in that lights submenu. A checkbox to show a light or a group, or both. That way you may have a grouped lights and single lights but only show an item for each.

**Comment by rektdeckard** [comment]
Solid idea. The Hue Bridge automatically generates a hidden group containing all you lights, so that's what you're looking at. The problem I had in filtering them is that the group name is autogenerated by the bridge, and I don't think it's the same on every device.

Checkboxes to show and hide groups, as well as a way to collapse them, is an absolute must add feature for the next major iteration.

**Comment by 9812ga98sd** [comment]
Great!! see that is why i delete huetero :-) literally  your first version was so much better.

**Comment by rektdeckard** [comment]
@9812ga98sd this feature is now live, each of your groups are individually collapsible/expandable. I added this feature over a week ago but forgot to close this issue!

**Comment by 9812ga98sd** [comment]
i downloaded the windows client but could not see any changes.

**Comment by rektdeckard** [comment]
Haven't put up the new installer yet. It will go out in the next hour or so! Feature is currently live in the web version.

**Comment by 9812ga98sd** [comment]
Got it, works great.

**Comment by 9812ga98sd** [comment]
Is there a way to collapse the settings left hand side area? Also to collapse the right colour choice area just to leave the middle section?
